Vagrant.configure("2") do |config|

	config.vm.box = "bento/ubuntu-22.04"
  
	# require plugin https://github.com/leighmcculloch/vagrant-docker-compose
	# config.vagrant.plugins = "vagrant-docker-compose"
  
	# install docker and docker-compose
	config.vm.provision :docker
	# config.vm.provision :docker_compose
	config.vm.provision :shell, :inline => "sysctl -w 'kernel.core_pattern=|/bin/false'", :run=> "always", :privileged => true  

	config.vm.provider "virtualbox" do |vb|
	  vb.customize ["modifyvm", :id, "--ioapic", "on"]
	  vb.customize ["modifyvm", :id, "--memory", "2048"]
	  vb.customize ["modifyvm", :id, "--cpus", "2"]
	end
  
  end